name: 'Tests'
      
on:
  workflow_dispatch:

  schedule:
    - cron: '20 4 2 * *'
  
  push:
    paths:
      - 'test.yml'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'git / checkout'
        uses: actions/checkout@v4

      - name: 'haskell / setup'
        uses: haskell-actions/setup@v2.8.2
        with:
          ghc-version: 9.6.7
          cabal-version: 3.12.1.0

      - name: 'cabal / test'
        run: cabal test
